### ISSUE TITLE
Includes humans?

### ISSUE THREAD

**Issue by NakedMoleRatScientist** [evolverine/covid-19-anki-deck#21]
With Anthony Fauci popping up in the news, it might be a good idea to know who's who in the government in fighting or impending the pandemic, especially medical experts. 

People who may be included: heads of states, NGO heads, WHO, people in charge of the CDC, etc.

Given that it's politically charged, historical determination will have to wait until historians weigh in, unless we just stick with uncontroversial tests.

**Comment by evolverine** [comment]
It might be useful indeed, but it would make it very US-centric, and I'd like this deck to be as global as possible (and adding the names of top officials from all countries isn't realistic). Also, I'm hoping that through the sources we use people can get a sense of the organisations that are credible (WHO, CDC, NHS), rather than particular individuals in them. Hope it makes sense?

But then again, I can totally imagine a spin-off of this deck, called something like COVID_19_evolution_USA that would add cards specifically for the USA, and would stay up to date with this deck for the more generic information regarding COVID-19. You'd be more than welcome to start it, of course.
