### ISSUE TITLE
Add context cues on all cards where necessary.

### ISSUE THREAD

**Issue by aleksejrs** [evolverine/covid-19-anki-deck#23]
I move all the cards into another deck. Some of the cards do not mention COVID-19 or biology, and some of them become confusing because of that.

Oh wait, are they supposed to have a special background? I am using Anki 2.0.x; it probably needs different CSS then, but could that give some of the cards too much context if only COVID-19-specific cards have it...?

**Comment by evolverine** [comment]
Yes, (at least in Anki 2.1.x) they have a background that's meant to give them context. And what do you mean by too much context, in this case? Do you have an example of a card that might have too much context with the background?

In terms of context when the background doesn't work for you, they are also all tagged with the "covid-19" tag. You could [use this with javascript to display a visual difference (perhaps an icon) if the card has that tag](https://anki.tenderapp.com/discussions/ankimobile/5468-conditional-render-based-on-tag). Although each update from github would erase your tag changes (I think).

Having said that, if you ever use AnkiDroid to study, that shows the background correctly. (I'd be interested to know how the iOS clients handle it, if you, or someone else use them.)

On a separate note, is there no way for you to upgrade to the latest Anki client?

**Comment by aleksejrs** [comment]
> Do you have an example of a card that might have too much context with the background?

The mortality rate (?) of flu is not specific to COVID-19.

> On a separate note, is there no way for you to upgrade to the latest Anki client?

It's too slow for reviews here.

**Comment by evolverine** [comment]
> The mortality rate (?) of flu is not specific to COVID-19.

I see what you mean. Indeed, in my mind the context is still COVID-19, because I want people to have at least some data in debates exploring the differences and similarities with the flu, but for others these might not be that connected indeed. I wish there were more ways in which people could customize their notes to diverge from the main deck without being overwritten each time, but for now that's what we're working with.

> It's too slow for reviews here.

I see. And were you able to make the javascript work? I remember using such javascript code in Anki 2.0.x and it working well (I'm not sure if I had to install any add-ons, though).

**Comment by aleksejrs** [comment]
> And were you able to make the javascript work?

Since I am using a modified note type, I simply added a text hint.

**Comment by evolverine** [comment]
I'll close the ticket, as I haven't heard back from you in a while. But feel free to reopen it (or just add more comments) if there's anything else we can work out in relation to this.
