### ISSUE TITLE
General Feedback´

### ISSUE THREAD

**Issue by StreitDa** [evolverine/covid-19-anki-deck#24]
First of all, let me thank you for making this deck. I had something similar in mind, but alas, I was too busy.

I've found a couple of things that I think could be improved but don't want to open a sperate issue for every item, because I don't know how many issues you consider a bug.

First: I think the "context" on the cards could be moved to a less visible location. When I came across the first card having a context field, I started reading from the top and thought the card had an error. (Because, I take it me and many others expect the first thing that appears on the card to be the question). So I think the context-field could be displayed below the question or maybe typeset in a lighter shade of grey.

The second minor nitpick I have is with the "definition" cards. I would use an extra "What is:" in front of them. I understand that this has not been done to be able to use a single note type. But I imagine, if I come across the covid-19 background in six months and see a card with the front "Incubation period", I will probably try to remember the (estimated) incubation period for covid-19 and not what the words mean. I think one should bite the bullet here and just add another note type.

Then there are a couple of cards where I think the content could me made more precise. I'll go through them one-by-one

Q: "The reason we are (currently, 2020.04) not able to test everyone, or even everyone with symptoms",
A: "Lack of sufficient testing equipment",
This seems overly broad. It is certainly true of europe, africa, australia and the americas, but (afaik) not of every country in asia. I suggest using "most countries" instead of "we" here.

Q"Information that's impossible to know",
A:"Mortality data for ongoing cases",
I just don't see the connection here. Surely there is a lot more that is impossible to know then just the mortality rate. I would either refrase the card: Can we know the mortality data for ongoing cases? - No. Delete the card (my favourite) or change it to something asking a why question: (I.e. Why can we know the mortality data for ongoing cases)

Q: Tuberculosis
A: "Bacterial infectious disease caused by Mycobacterium tuberculosis",
First (even though there is another card for this, I would mention that tuberculosis is first and foremost a disease of the lungs. If you deem it important that it is a bacterial disease, make one (or two) new cards asking for the name of the bacterium (and what kind of pathogen causes the disease)

Q: "Information that we don't know due to limited resources",
A: "Who is infected and who isn't",
See above; I just don't see the connection between question and answer.

Q:  "Which pre-existing condition* seems to worsen prospects the most for those infected with SARS-CoV-2?",
A: "cardiovascular disease<br><br>* <span style=\"font-weight:normal\">class of conditions</span>",
I don't like the asterisk. Personally, I would prefer to just move the "class of" to the front. Another thing (shared by a different card), pre-existing condition feels to much like US health care system to me. I would just use comorbitity here. As you can tell, I am not a native english speaker though, so take this with a grain of salt.

Q:  "How does the size of the genetic material in coronaviruses compare to other RNA viruses?",
A:   "Coronaviruses have the largest genomes of all RNA viruses",
I would add (like the original source does) that they have the largest genome of all KNOWN RNA viruses.

Q: "Classification of viruses according to their genetic material",
A; "DNA and RNA viruses",
I don't really like this because it is not precise. When I first came across this card, I was thinking of the [Baltimore Classification](https://en.wikipedia.org/wiki/Baltimore_classification). Maybe rephrase as "What is the simplest classification of viruses according to their genetic material?"

Q: "How many coronaviruses are known to cause disease in humans?",
A: 7
I know that a later card asks for the number of endemic coronaviruses, but I still think this might confuse some users. SARS is extinct after all. I don't have a good solution. Maybe add that not all of them exist anymore in parentheses?

Q: "For how long did viable SARS-CoV-2 remain in aerosol?",
A: "at least 3 hours"
While there is a context field linking the study, I still find this (and to a lesser degree the other cards made for this study) misleading. I think some users will come away with the conclusion that there might aerosol transmission is far more dangerous than it really is. First, (and this is not to criticize the authors of the study) this result comes from highly artificial labaratory conditions (see the supplement in the source you linked). Conditions outside (wind, UV, etc.) will disperse any infectious aerosol far quicker. The second point is that while there was still viable virus detectable it is doubtful that it was an infectious dose, even in lab conditions.
That being said, I don't really have a good idea on how to make this card better :/

Q:  "Why is it hard to estimate the case fatality rate (CFR) for COVID-19?",
A:  "<div>The numbers do not reflect reality</div><div></div>", (too much divs!!)
I don't really understand this card to be honest. What numbers don't reflect reality? Surely we have some knowledge of the diagnosed cases (they were diagnosed after all) and we must be able to tell if these cases die with a reasonable amount of confidence. Am I missing something here?

Q: "Median number of days after infection that the virus was still detected in patients",
A: "20"
For some reason the lancet won't let me view the original study, so I might be wrong here, but afaik, this means that viral RNA can still be found not that the virus is still infectious. So again, I think some users walk away from this and think that most people are infectious until day 20 after infection, which is for all we know not the case.

The same goes for the question with "maximum" instead of "median"

Q: "How can recovered patients help those struggling with the disease?",
A:  "By donating plasma (which contains antibodies)",
I find this to be too specific for the question, surely they could also volunteer by shopping for vulnerable groups or providing at-home care for family-members or something. Also (as far as I know) it is not clear yet whether antibody therapy really works and if every recovered patient is a viable donor (but please corrext me if I'm wrong here).

Q: When to use masks?
A: - When coughing or sneezing
    - When caring for someone with a suspected or confirmed infection
This card I find somewhat dangerous. A face mask is probably somewhat useful to prevent coughing and sneezing from infecting others (also breathing and talking). But it is a different mask then will protect you from becoming infected (the second part of the answer). A mask that protects you against the virus (i.e. ffp3) usually has a valve that releases all the air you exhale(!) unfiltered. In my opinion, this card conflates to very different uses of masks. Those to protect others (any old thing will probably help a bit) and those that protect oneself (a piece of cloth will probably not reduce risk of infection by much, a ffp3 mask will).

I hope this wasn't too much for a single issue.
Again let me thank you for a wonderful deck and I hope that at least some points I raised will make it even a little better.

**Comment by evolverine** [comment]
Let me also start by thanking you for all your feedback! I'll take it point by point:

1. context — I agree, will do in the next few days
2. definition — another simple way it could work is to just add "(definition)" to the front of the card, no? I also like using javascript, and that could easily solve it via a "definition" tag and displaying that as an icon / text, etc.
3. "The reason we are ..." — how about "The main reason not everyone suspected* can be tested for COVID-19 in most countries
* either with (even mild) symptoms, or identified as high probability through contact tracing"
4. "Information that's impossible to know" — I wonder if the difference is on how we define "impossible". I use it to mean "even if we had all the resources and methods at our disposal", a sort of synonym of "logically impossible" (say, apart from a good prediction), because the events we care about (the deaths) have yet to happen. If so, I could define "impossible" with an asterisk as used above. Otherwise, what other information is impossible (in this sense) to know?
(I'll continue this in a few hours.)

**Comment by evolverine** [comment]
5. Tuberculosis  — the challenge here is that there defining it as, say, a "bacterial infection of the lungs" doesn't suffice, because there are others that we don't call tuberculosis, so the definition is incomplete. So, at least in my mind, the definition needs to contain the name of the bacteria, which constrains the infection to being precisely TBC. Also, there already exists another note asking which bacteria cause TBC (search for "Bacteria that cause tuberculosis")
6. "Information that we don't know due to limited resources"  — this series of cards is trying to explain, in as plain language as possible, why one cannot rely on the official numbers to assess the spread, or the mortality of the disease. If you search for "Official numbers not reflecting the ongoing reality of the COVID-19 spread" (in the context field), I hope all the notes together are starting to make sense as a whole. But if you have a better way of explaining this (without creating notes with lists longer than 3 items; and even those I'd avoid), by all means I'll be open to reviewing it.
7. "Which pre-existing condition*..." — agreed, done.
8.  "Why is it hard to estimate the case fatality rate (CFR) for COVID-19?" — yes, if you read through the sources in that note, you'll see that the CFR is very hard to estimate, due to asymptomatic and low-symptomatic cases, and a few other challenging issues.

**Comment by evolverine** [comment]
9. Well, in that Lancet study they say "Because coronavirus RNA detection is more sensitive than virus isolation, most studies have used qualitative or quantitative viral RNA tests as a potential marker for infectious coronavirus" and that "This has important implications for both patient isolation decision making and guidance around the length of antiviral treatment". I'm not sure whether it implies that the person is infectious after those 20 days, or likely infectious, or whether we simply don't know yet. In case you've seen more up-to-date information, do let me know.
10. "How can recovered patients help those struggling with the disease?" — you're right, it was very unspecific, I'll reword that. I've also just done a search for more recent data, and it seems that, [at least in the US it's still under study, and classified as experimental therapy](https://hub.jhu.edu/2020/03/27/covid-19-sera-funding/); the same [applies to the UK](https://www.nhsbt.nhs.uk/how-you-can-help/convalescent-plasma-clinical-trial/). I've included a few more questions on the basic concepts there (plasma, convalescence, etc.)
11. You're right, I had that note (about the masks) marked because I wasn't satisfied with it and didn't have the time to look at it in more depth. Would you like to make a pull request with improvements and good sources?

**Comment by evolverine** [comment]
Thank you yet again for the work of providing the feedback. The deck is definitely better because of it. Let me know what you think about the various points I made. In the meantime, I've just pushed a few changes and new questions that I created while dealing with said points.

**Comment by aleksejrs** [comment]
@evolverine 

11. Are the marks copied to my deck intentionally? Are all the marked cards to be somewhat wary about? I think it should be mentioned in the README, because people may be using marks for something including deleting, moving or even exporting elsewhere.

**Comment by evolverine** [comment]
11. Thank you, @aleksejrs, for mentioning it. I was using the `marked` tag as a way to remind me that some cards still need some polishing, or some more information checking. But you're right, some people might use them in different ways. I just went through them and made the necessary changes.

**Comment by StreitDa** [comment]
Hey again, sorry for the late reply; Unfortunately, I am really strapped for time at the moment. I've seen that you already addressed a lot of my worries. Thanks for that. 

>     1. formation that's impossible to know" — I wonder if the difference is on how we define "impossible". I use it to mean "even if we had all the resources and methods at our disposal", a sort of synonym of "logically impossible" (say, apart from a good prediction), because the events we care about (the deaths) have yet to happen. If so, I could define "impossible" with an asterisk as used above. Otherwise, what othe
My worry with this and the other question was more that: "What's impossible to know?" allows for all kinds of possible answers: Who was patient zero? What is the rate of infection? Will we be able to eliminate the disease? What will the overall death toll be?

So what this card (imho) does is condition you to reply to the front without any substantial connection. In my personal decks, I try to avoid cards like this at all costs, because I find that in a few months I cannot remember them and the knowledge feels disconnected.

>     1. Tuberculosis  — the challenge here is that there defining it as, say, a "bacterial infection of the lungs" doesn't suffice, because there are others that we don't call tuberculosis, so the definition is incomplete. So, at least in my mind, the definition needs to contain the name of the bacteria, which constrains the infection to being precisely TBC. 

I understand the reasoning; I just think that if someone asks you what Tuberculosis is, you don't have to be able to give something like an actual definition. It would be different, if the question was reversed and you were asked what the disease caused by myobacterium tuberculosis was.

**Comment by StreitDa** [comment]
>     1. Well, in that Lancet study they say "Because coronavirus RNA detection is more sensitive than virus isolation, most studies have used qualitative or quantitative viral RNA tests as a potential marker for infectious coronavirus" and that "This has important implications for both patient isolation decision making and guidance around the length of antiviral treatment". I'm not sure whether it implies that the person is infectious after those 20 days, or likely infectious, or whether we simply don't know yet. In case you've seen more up-to-date information, do let me know.

Cool thanks, I couldn't access the study. I will try to find information that settles this question, but it might take me a while.

Edit: I haven't had time to really read all of it and think about it, but there is this nature study that supports (at least some) of my initial suspicions:
[Temporal dynamics in viral shedding and transmissibility of COVID-19](https://www.nature.com/articles/s41591-020-0869-5)

"Another study from Wuhan reported that virus was detected for a median of 20 days (up to 37 days among survivors) after symptom onset, but infectiousness may decline significantly 8 days after symptom onset, as live virus could no longer be cultured (according to Wölfel and colleagues[11]). "

The study they cite is also in nature: 
[Virological assessment of hospitalized patients with COVID-2019](https://www.nature.com/articles/s41586-020-2196-x)

I have neither the expertise nor the time to verify if this is a high enough confidence that infectiousness is long gone before day 20; But maybe it warrants formulating the card a bit more carefully.

**Comment by evolverine** [comment]
> So what this card (imho) does is condition you to reply to the front without any substantial connection. In my personal decks, I try to avoid cards like this at all costs

I also try to avoid too generic cards. For this reason the context of these cards is meant to constrain the possible set of answers — if the context is "Official count not reflecting the ongoing reality of the COVID-19 spread", then it's clearer (I hope) that "what's impossible to know" is only related to having accurate counts / numbers of the spread of the illness. If you have any suggestions for wording the context or the questions better while achieving the same result (helping transmit the difference between the "official" and "actual" spread of the virus, plus the challenges of various official bodies of reporting the numbers accurately), I'll be glad to consider and integrate them.

> I just think that if someone asks you what Tuberculosis is, you don't have to be able to give something like an actual definition

True, though if someone does indeed ask us what Tuberculosis is, we don't actually have to answer with all the content of our Anki cards. In this case I seem to value accuracy / correctness when learning more than simplicity. This also has the benefit of averting the potential, in the same imagined conversation, of being told 'yes, but there are many infections of the lungs".

Finally, thank you for the articles. I've added them to my reading list, I hope to get to them in the next few days.

**Comment by evolverine** [comment]
(feel free to reopen the issue if you feel there remain unaddressed topics)
